# Copyright 2013, 2014, 2015, 2016 Clerk Ma
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.

#libicuuc
$(LIBICU_PATH)/icu-src/source/common/pluralmap.cpp
$(LIBICU_PATH)/icu-src/source/common/uloc_keytype.cpp
$(LIBICU_PATH)/icu-src/source/common/unifiedcache.cpp
$(LIBICU_PATH)/icu-src/source/common/simpleformatter.cpp
$(LIBICU_PATH)/icu-src/source/common/sharedobject.cpp
$(LIBICU_PATH)/icu-src/source/common/ulistformatter.cpp
$(LIBICU_PATH)/icu-src/source/common/listformatter.cpp
$(LIBICU_PATH)/icu-src/source/common/icuplug.cpp
$(LIBICU_PATH)/icu-src/source/common/icudataver.c
$(LIBICU_PATH)/icu-src/source/common/uloc_tag.c
$(LIBICU_PATH)/icu-src/source/common/ulist.c
$(LIBICU_PATH)/icu-src/source/common/propsvec.c
$(LIBICU_PATH)/icu-src/source/common/ucnvsel.cpp
$(LIBICU_PATH)/icu-src/source/common/dtintrv.cpp
$(LIBICU_PATH)/icu-src/source/common/wintz.c
$(LIBICU_PATH)/icu-src/source/common/cwchar.c
$(LIBICU_PATH)/icu-src/source/common/locbased.cpp
$(LIBICU_PATH)/icu-src/source/common/parsepos.cpp
$(LIBICU_PATH)/icu-src/source/common/util_props.cpp
$(LIBICU_PATH)/icu-src/source/common/util.cpp
$(LIBICU_PATH)/icu-src/source/common/punycode.cpp
$(LIBICU_PATH)/icu-src/source/common/uts46.cpp
$(LIBICU_PATH)/icu-src/source/common/usprep.cpp
$(LIBICU_PATH)/icu-src/source/common/uidna.cpp
$(LIBICU_PATH)/icu-src/source/common/servslkf.cpp
$(LIBICU_PATH)/icu-src/source/common/servrbf.cpp
$(LIBICU_PATH)/icu-src/source/common/servlkf.cpp
$(LIBICU_PATH)/icu-src/source/common/servlk.cpp
$(LIBICU_PATH)/icu-src/source/common/servls.cpp
$(LIBICU_PATH)/icu-src/source/common/servnotf.cpp
$(LIBICU_PATH)/icu-src/source/common/serv.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbitblb.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbistbl.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbisetb.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbiscan.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbirb.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbinode.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbidata.cpp
$(LIBICU_PATH)/icu-src/source/common/rbbi.cpp
$(LIBICU_PATH)/icu-src/source/common/filteredbrk.cpp
$(LIBICU_PATH)/icu-src/source/common/dictbe.cpp
$(LIBICU_PATH)/icu-src/source/common/brkeng.cpp
$(LIBICU_PATH)/icu-src/source/common/ubrk.cpp
$(LIBICU_PATH)/icu-src/source/common/brkiter.cpp
$(LIBICU_PATH)/icu-src/source/common/uarrsort.c
$(LIBICU_PATH)/icu-src/source/common/unifunct.cpp
$(LIBICU_PATH)/icu-src/source/common/unifilt.cpp
$(LIBICU_PATH)/icu-src/source/common/caniter.cpp
$(LIBICU_PATH)/icu-src/source/common/ruleiter.cpp
$(LIBICU_PATH)/icu-src/source/common/usetiter.cpp
$(LIBICU_PATH)/icu-src/source/common/uniset.cpp
$(LIBICU_PATH)/icu-src/source/common/uset.cpp
$(LIBICU_PATH)/icu-src/source/common/uniset_closure.cpp
$(LIBICU_PATH)/icu-src/source/common/uniset_props.cpp
$(LIBICU_PATH)/icu-src/source/common/uset_props.cpp
$(LIBICU_PATH)/icu-src/source/common/unisetspan.cpp
$(LIBICU_PATH)/icu-src/source/common/bmpset.cpp
$(LIBICU_PATH)/icu-src/source/common/utrie2_builder.cpp
$(LIBICU_PATH)/icu-src/source/common/utrie2.cpp
$(LIBICU_PATH)/icu-src/source/common/utrie.cpp
$(LIBICU_PATH)/icu-src/source/common/unames.cpp
$(LIBICU_PATH)/icu-src/source/common/usc_impl.c
$(LIBICU_PATH)/icu-src/source/common/uscript_props.cpp
$(LIBICU_PATH)/icu-src/source/common/uscript.c
$(LIBICU_PATH)/icu-src/source/common/ushape.cpp
$(LIBICU_PATH)/icu-src/source/common/ubidiln.c
$(LIBICU_PATH)/icu-src/source/common/ubidiwrt.c
$(LIBICU_PATH)/icu-src/source/common/ubidi.c
$(LIBICU_PATH)/icu-src/source/common/ubidi_props.c
$(LIBICU_PATH)/icu-src/source/common/propname.cpp
$(LIBICU_PATH)/icu-src/source/common/ucase.cpp
$(LIBICU_PATH)/icu-src/source/common/uprops.cpp
$(LIBICU_PATH)/icu-src/source/common/uchar.c
$(LIBICU_PATH)/icu-src/source/common/patternprops.cpp
$(LIBICU_PATH)/icu-src/source/common/uiter.cpp
$(LIBICU_PATH)/icu-src/source/common/uchriter.cpp
$(LIBICU_PATH)/icu-src/source/common/schriter.cpp
$(LIBICU_PATH)/icu-src/source/common/chariter.cpp
$(LIBICU_PATH)/icu-src/source/common/loadednormalizer2impl.cpp
$(LIBICU_PATH)/icu-src/source/common/unormcmp.cpp
$(LIBICU_PATH)/icu-src/source/common/unorm.cpp
$(LIBICU_PATH)/icu-src/source/common/normlzr.cpp
$(LIBICU_PATH)/icu-src/source/common/filterednormalizer2.cpp
$(LIBICU_PATH)/icu-src/source/common/normalizer2.cpp
$(LIBICU_PATH)/icu-src/source/common/normalizer2impl.cpp
$(LIBICU_PATH)/icu-src/source/common/ustr_titlecase_brkiter.cpp
$(LIBICU_PATH)/icu-src/source/common/unistr_titlecase_brkiter.cpp
$(LIBICU_PATH)/icu-src/source/common/ustrcase_locale.cpp
$(LIBICU_PATH)/icu-src/source/common/unistr_case_locale.cpp
$(LIBICU_PATH)/icu-src/source/common/utext.cpp
$(LIBICU_PATH)/icu-src/source/common/ustr_wcs.cpp
$(LIBICU_PATH)/icu-src/source/common/ustrtrns.cpp
$(LIBICU_PATH)/icu-src/source/common/ustrfmt.c
$(LIBICU_PATH)/icu-src/source/common/cstring.c
$(LIBICU_PATH)/icu-src/source/common/ucasemap_titlecase_brkiter.cpp
$(LIBICU_PATH)/icu-src/source/common/ucasemap.cpp
$(LIBICU_PATH)/icu-src/source/common/ustrcase.cpp
$(LIBICU_PATH)/icu-src/source/common/ustring.cpp
$(LIBICU_PATH)/icu-src/source/common/utf_impl.c
$(LIBICU_PATH)/icu-src/source/common/unistr_props.cpp
$(LIBICU_PATH)/icu-src/source/common/unistr_case.cpp
$(LIBICU_PATH)/icu-src/source/common/unistr.cpp
$(LIBICU_PATH)/icu-src/source/common/unistr_cnv.cpp
$(LIBICU_PATH)/icu-src/source/common/ustr_cnv.cpp
$(LIBICU_PATH)/icu-src/source/common/appendable.cpp
$(LIBICU_PATH)/icu-src/source/common/dictionarydata.cpp
$(LIBICU_PATH)/icu-src/source/common/ucharstrieiterator.cpp
$(LIBICU_PATH)/icu-src/source/common/ucharstriebuilder.cpp
$(LIBICU_PATH)/icu-src/source/common/ucharstrie.cpp
$(LIBICU_PATH)/icu-src/source/common/bytestrieiterator.cpp
$(LIBICU_PATH)/icu-src/source/common/bytestrie.cpp
$(LIBICU_PATH)/icu-src/source/common/bytestriebuilder.cpp
$(LIBICU_PATH)/icu-src/source/common/stringtriebuilder.cpp
$(LIBICU_PATH)/icu-src/source/common/stringpiece.cpp
$(LIBICU_PATH)/icu-src/source/common/bytestream.cpp
$(LIBICU_PATH)/icu-src/source/common/locresdata.cpp
$(LIBICU_PATH)/icu-src/source/common/loclikely.cpp
$(LIBICU_PATH)/icu-src/source/common/locdspnm.cpp
$(LIBICU_PATH)/icu-src/source/common/locdispnames.cpp
$(LIBICU_PATH)/icu-src/source/common/locavailable.cpp
$(LIBICU_PATH)/icu-src/source/common/locutil.cpp
$(LIBICU_PATH)/icu-src/source/common/locid.cpp
$(LIBICU_PATH)/icu-src/source/common/uloc.cpp
$(LIBICU_PATH)/icu-src/source/common/locmap.c
$(LIBICU_PATH)/icu-src/source/common/ucat.c
$(LIBICU_PATH)/icu-src/source/common/messagepattern.cpp
$(LIBICU_PATH)/icu-src/source/common/ucurr.cpp
$(LIBICU_PATH)/icu-src/source/common/resbund_cnv.cpp
$(LIBICU_PATH)/icu-src/source/common/resbund.cpp
$(LIBICU_PATH)/icu-src/source/common/uresdata.cpp
$(LIBICU_PATH)/icu-src/source/common/ures_cnv.c
$(LIBICU_PATH)/icu-src/source/common/uresbund.cpp
$(LIBICU_PATH)/icu-src/source/common/resource.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnv_ct.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_set.c
$(LIBICU_PATH)/icu-src/source/common/ucnvdisp.c
$(LIBICU_PATH)/icu-src/source/common/ucnvisci.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_lmb.c
$(LIBICU_PATH)/icu-src/source/common/ucnvhz.c
$(LIBICU_PATH)/icu-src/source/common/ucnv2022.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnvmbcs.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnv_ext.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnvbocu.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnvscsu.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_u32.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_u16.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_u8.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_u7.c
$(LIBICU_PATH)/icu-src/source/common/ucnvlat1.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_err.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_cb.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_io.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnv_cnv.c
$(LIBICU_PATH)/icu-src/source/common/ucnv_bld.cpp
$(LIBICU_PATH)/icu-src/source/common/ucnv.c
$(LIBICU_PATH)/icu-src/source/common/uvectr64.cpp
$(LIBICU_PATH)/icu-src/source/common/uvectr32.cpp
$(LIBICU_PATH)/icu-src/source/common/ustack.cpp
$(LIBICU_PATH)/icu-src/source/common/uvector.cpp
$(LIBICU_PATH)/icu-src/source/common/ustrenum.cpp
$(LIBICU_PATH)/icu-src/source/common/uenum.c
$(LIBICU_PATH)/icu-src/source/common/uhash_us.cpp
$(LIBICU_PATH)/icu-src/source/common/uhash.c
$(LIBICU_PATH)/icu-src/source/common/utrace.c
$(LIBICU_PATH)/icu-src/source/common/ucol_swp.cpp
$(LIBICU_PATH)/icu-src/source/common/udataswp.c
$(LIBICU_PATH)/icu-src/source/common/umapfile.c
$(LIBICU_PATH)/icu-src/source/common/udatamem.c
$(LIBICU_PATH)/icu-src/source/common/ucmndata.c
$(LIBICU_PATH)/icu-src/source/common/udata.cpp
$(LIBICU_PATH)/icu-src/source/common/cstr.cpp
$(LIBICU_PATH)/icu-src/source/common/charstr.cpp
$(LIBICU_PATH)/icu-src/source/common/cmemory.c
$(LIBICU_PATH)/icu-src/source/common/uobject.cpp
$(LIBICU_PATH)/icu-src/source/common/uinit.cpp
$(LIBICU_PATH)/icu-src/source/common/ucln_cmn.cpp
$(LIBICU_PATH)/icu-src/source/common/umutex.cpp
$(LIBICU_PATH)/icu-src/source/common/uinvchar.c
$(LIBICU_PATH)/icu-src/source/common/utypes.c
$(LIBICU_PATH)/icu-src/source/common/umath.c
$(LIBICU_PATH)/icu-src/source/common/putil.cpp
$(LIBICU_PATH)/icu-src/source/common/errorcode.cpp
#libicui18n
$(LIBICU_PATH)/icu-src/source/i18n/dayperiodrules.cpp
$(LIBICU_PATH)/icu-src/source/i18n/visibledigits.cpp
$(LIBICU_PATH)/icu-src/source/i18n/decimfmtimpl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/smallintformatter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/affixpatternparser.cpp
$(LIBICU_PATH)/icu-src/source/i18n/precision.cpp
$(LIBICU_PATH)/icu-src/source/i18n/pluralaffix.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitaffixesandpadding.cpp
$(LIBICU_PATH)/icu-src/source/i18n/valueformatter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitaffix.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitformatter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitinterval.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitgrouping.cpp
$(LIBICU_PATH)/icu-src/source/i18n/scientificnumberformatter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/sharedbreakiterator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/measunit.cpp
$(LIBICU_PATH)/icu-src/source/i18n/quantityformatter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/reldatefmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uregion.cpp
$(LIBICU_PATH)/icu-src/source/i18n/identifier_info.cpp
$(LIBICU_PATH)/icu-src/source/i18n/scriptset.cpp
$(LIBICU_PATH)/icu-src/source/i18n/region.cpp
$(LIBICU_PATH)/icu-src/source/i18n/gender.cpp
$(LIBICU_PATH)/icu-src/source/i18n/compactdecimalformat.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tzfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tzgnames.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tznames_impl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tznames.cpp
$(LIBICU_PATH)/icu-src/source/i18n/alphaindex.cpp
$(LIBICU_PATH)/icu-src/source/i18n/decContext.c
$(LIBICU_PATH)/icu-src/source/i18n/decNumber.c
$(LIBICU_PATH)/icu-src/source/i18n/ufieldpositer.cpp
$(LIBICU_PATH)/icu-src/source/i18n/fpositer.cpp
$(LIBICU_PATH)/icu-src/source/i18n/fphdlimp.cpp
$(LIBICU_PATH)/icu-src/source/i18n/vzone.cpp
$(LIBICU_PATH)/icu-src/source/i18n/zrule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ztrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/smpdtfst.cpp
$(LIBICU_PATH)/icu-src/source/i18n/decfmtst.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uspoof_wsconf.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uspoof_conf.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uspoof_build.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uspoof_impl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uspoof.cpp
$(LIBICU_PATH)/icu-src/source/i18n/currpinf.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tmutfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tmutamt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tmunit.cpp
$(LIBICU_PATH)/icu-src/source/i18n/udateintervalformat.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dtitvinf.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dtitvfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/selfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/plurfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/plurrule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/upluralrules.cpp
$(LIBICU_PATH)/icu-src/source/i18n/standardplural.cpp
$(LIBICU_PATH)/icu-src/source/i18n/zonemeta.cpp
$(LIBICU_PATH)/icu-src/source/i18n/vtzone.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tztrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tzrule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbtz.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dtrule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/basictz.cpp
$(LIBICU_PATH)/icu-src/source/i18n/winnmfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/windtfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/wintzimpl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/inputext.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csrutf8.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csrucode.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csrsbcs.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csrmbcs.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csrecog.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csr2022.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csmatch.cpp
$(LIBICU_PATH)/icu-src/source/i18n/csdetect.cpp
$(LIBICU_PATH)/icu-src/source/i18n/utmscale.c
$(LIBICU_PATH)/icu-src/source/i18n/measure.cpp
$(LIBICU_PATH)/icu-src/source/i18n/currunit.cpp
$(LIBICU_PATH)/icu-src/source/i18n/curramt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/currfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/measfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ulocdata.c
$(LIBICU_PATH)/icu-src/source/i18n/uregexc.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uregex.cpp
$(LIBICU_PATH)/icu-src/source/i18n/regeximp.cpp
$(LIBICU_PATH)/icu-src/source/i18n/regextxt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/regexst.cpp
$(LIBICU_PATH)/icu-src/source/i18n/repattrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rematch.cpp
$(LIBICU_PATH)/icu-src/source/i18n/regexcmp.cpp
$(LIBICU_PATH)/icu-src/source/i18n/brktrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/transreg.cpp
$(LIBICU_PATH)/icu-src/source/i18n/quant.cpp
$(LIBICU_PATH)/icu-src/source/i18n/nortrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uni2name.cpp
$(LIBICU_PATH)/icu-src/source/i18n/name2uni.cpp
$(LIBICU_PATH)/icu-src/source/i18n/anytrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/toupptrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tolowtrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/titletrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/casetrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/remtrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/nultrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbt_set.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbt_rule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbt_pars.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbt_data.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/cpdtrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/tridpars.cpp
$(LIBICU_PATH)/icu-src/source/i18n/strrepl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/funcrepl.cpp
$(LIBICU_PATH)/icu-src/source/i18n/unesctrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/esctrn.cpp
$(LIBICU_PATH)/icu-src/source/i18n/utrans.cpp
$(LIBICU_PATH)/icu-src/source/i18n/translit.cpp
$(LIBICU_PATH)/icu-src/source/i18n/stsearch.cpp
$(LIBICU_PATH)/icu-src/source/i18n/search.cpp
$(LIBICU_PATH)/icu-src/source/i18n/usearch.cpp
$(LIBICU_PATH)/icu-src/source/i18n/strmatch.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationfastlatinbuilder.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationbuilder.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationruleparser.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationweights.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationdatabuilder.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationrootelements.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationroot.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rulebasedcollator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationkeys.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationfastlatin.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationcompare.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationsets.cpp
$(LIBICU_PATH)/icu-src/source/i18n/uitercollationiterator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/utf8collationiterator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/utf16collationiterator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationiterator.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationfcd.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationdatawriter.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationdatareader.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationtailoring.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationdata.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collationsettings.cpp
$(LIBICU_PATH)/icu-src/source/i18n/collation.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucol_sit.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucol_res.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucol.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucoleitr.cpp
$(LIBICU_PATH)/icu-src/source/i18n/bocsu.cpp
$(LIBICU_PATH)/icu-src/source/i18n/sortkey.cpp
$(LIBICU_PATH)/icu-src/source/i18n/coll.cpp
$(LIBICU_PATH)/icu-src/source/i18n/coleitr.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ethpccal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dangical.cpp
$(LIBICU_PATH)/icu-src/source/i18n/coptccal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/cecal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/chnsecal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/indiancal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/hebrwcal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/gregoimp.cpp
$(LIBICU_PATH)/icu-src/source/i18n/japancal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/islamcal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/persncal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/buddhcal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/taiwncal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/astro.cpp
$(LIBICU_PATH)/icu-src/source/i18n/olsontz.cpp
$(LIBICU_PATH)/icu-src/source/i18n/simpletz.cpp
$(LIBICU_PATH)/icu-src/source/i18n/timezone.cpp
$(LIBICU_PATH)/icu-src/source/i18n/gregocal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/calendar.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucal.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucsdet.cpp
$(LIBICU_PATH)/icu-src/source/i18n/unumsys.cpp
$(LIBICU_PATH)/icu-src/source/i18n/numsys.cpp
$(LIBICU_PATH)/icu-src/source/i18n/rbnf.cpp
$(LIBICU_PATH)/icu-src/source/i18n/nfsubs.cpp
$(LIBICU_PATH)/icu-src/source/i18n/nfrule.cpp
$(LIBICU_PATH)/icu-src/source/i18n/nfrs.cpp
$(LIBICU_PATH)/icu-src/source/i18n/udatpg.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dtptngen.cpp
$(LIBICU_PATH)/icu-src/source/i18n/udat.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dtfmtsym.cpp
$(LIBICU_PATH)/icu-src/source/i18n/reldtfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/smpdtfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/datefmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/choicfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/fmtable_cnv.cpp
$(LIBICU_PATH)/icu-src/source/i18n/digitlst.cpp
$(LIBICU_PATH)/icu-src/source/i18n/dcfmtsym.cpp
$(LIBICU_PATH)/icu-src/source/i18n/decimalformatpattern.cpp
$(LIBICU_PATH)/icu-src/source/i18n/decimfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/unum.cpp
$(LIBICU_PATH)/icu-src/source/i18n/numfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/umsg.cpp
$(LIBICU_PATH)/icu-src/source/i18n/msgfmt.cpp
$(LIBICU_PATH)/icu-src/source/i18n/format.cpp
$(LIBICU_PATH)/icu-src/source/i18n/fmtable.cpp
$(LIBICU_PATH)/icu-src/source/i18n/ucln_in.cpp
#libicuio
$(LIBICU_PATH)/icu-src/source/io/ucln_io.cpp
$(LIBICU_PATH)/icu-src/source/io/ustream.cpp
$(LIBICU_PATH)/icu-src/source/io/sscanf.c
$(LIBICU_PATH)/icu-src/source/io/sprintf.c
$(LIBICU_PATH)/icu-src/source/io/ustdio.c
$(LIBICU_PATH)/icu-src/source/io/uscanf_p.c
$(LIBICU_PATH)/icu-src/source/io/uscanf.c
$(LIBICU_PATH)/icu-src/source/io/uprntf_p.c
$(LIBICU_PATH)/icu-src/source/io/uprintf.cpp
$(LIBICU_PATH)/icu-src/source/io/ufmt_cmn.c
$(LIBICU_PATH)/icu-src/source/io/ufile.c
$(LIBICU_PATH)/icu-src/source/io/locbund.cpp
#libicutu
$(LIBICU_PATH)/icu-src/source/tools/toolutil/ucln_tu.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/dbgutil.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/udbgutil.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/filetools.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/flagparser.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/ppucd.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/pkg_gencmn.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/pkg_genc.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/pkg_icu.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/writesrc.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/xmlparser.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/ucbuf.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/uparse.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/uoptions.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/ucmstate.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/ucm.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/denseranges.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/collationinfo.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/unewdata.c
$(LIBICU_PATH)/icu-src/source/tools/toolutil/toolutil.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/swapimpl.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/pkgitems.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/package.cpp
$(LIBICU_PATH)/icu-src/source/tools/toolutil/filestrm.c
#libicutest
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/ucln_ct.c
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/uperf.cpp
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/datamap.cpp
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/testdata.cpp
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/tstdtmod.cpp
$(LIBICU_PATH)/icu-src/source/tools/ctestfw/ctest.c
