/*
 *   DO NOT EDIT THIS FILE!
 *   It was created by squeeze.c from another file (see the Makefile).
 */

const char psheader[] = "\
/TeXDict 250 dict def TeXDict begin /N{def}def /B{bind def}N /S{exch}N\n\
/X{S N}B /TR{translate}N /vsize 11 72 mul N end TeXDict begin /SDict 200\n\
dict N SDict begin /@SpecialDefaults{/hs 612 N /vs 792 N /ho 0 N /vo 0 N\n\
/hsc 1 N /vsc 1 N /ang 0 N /CLIP 0 N /rwiSeen false N /rhiSeen false N\n\
/letter{}N /note{}N /a4{}N /legal{}N}B /@scaleunit 100 N /@hscale{\n\
@scaleunit div /hsc X}B /@vscale{@scaleunit div /vsc X}B /@hsize{/hs X\n\
/CLIP 1 N}B /@vsize{/vs X /CLIP 1 N}B /@clip{/CLIP 2 N}B /@hoffset{/ho X\n\
}B /@voffset{/vo X}B /@angle{/ang X}B /@rwi{10 div /rwi X /rwiSeen true\n\
N}B /@rhi{10 div /rhi X /rhiSeen true N}B /@llx{/llx X}B /@lly{/lly X}B\n\
/@urx{/urx X}B /@ury{/ury X}B /magscale true def end /@MacSetUp{\n\
userdict /md known{userdict /md get type /dicttype eq{userdict begin md\n\
length 10 add md maxlength ge{/md md dup length 20 add dict copy def}if\n\
end md begin /letter{}N /note{}N /legal{}N /od{txpose 1 0 mtx\n\
defaultmatrix dtransform S atan/pa X newpath clippath mark{transform{\n\
itransform moveto}}{transform{itransform lineto}}{6 -2 roll transform 6\n\
-2 roll transform 6 -2 roll transform{itransform 6 2 roll itransform 6 2\n\
roll itransform 6 2 roll curveto}}{{closepath}}pathforall newpath\n\
counttomark array astore /gc xdf pop ct 39 0 put 10 fz 0 fs 2\n\
F/|______Courier fnt invertflag{PaintBlack}if}N /txpose{pxs pys scale\n\
ppr aload pop por{noflips{pop S neg S TR pop 1 -1 scale}if xflip yflip\n\
and{pop S neg S TR 180 rotate 1 -1 scale ppr 3 get ppr 1 get neg sub neg\n\
ppr 2 get ppr 0 get neg sub neg TR}if xflip yflip not and{pop S neg S TR\n\
pop 180 rotate ppr 3 get ppr 1 get neg sub neg 0 TR}if yflip xflip not\n\
and{ppr 1 get neg ppr 0 get neg TR}if}{noflips{TR pop pop 270 rotate 1\n\
-1 scale}if xflip yflip and{TR pop pop 90 rotate 1 -1 scale ppr 3 get\n\
ppr 1 get neg sub neg ppr 2 get ppr 0 get neg sub neg TR}if xflip yflip\n\
not and{TR pop pop 90 rotate ppr 3 get ppr 1 get neg sub neg 0 TR}if\n\
yflip xflip not and{TR pop pop 270 rotate ppr 2 get ppr 0 get neg sub\n\
neg 0 S TR}if}ifelse scaleby96{ppr aload pop 4 -1 roll add 2 div 3 1\n\
roll add 2 div 2 copy TR .96 dup scale neg S neg S TR}if}N /cp{pop pop\n\
showpage pm restore}N end}if}if}N /normalscale{Resolution 72 div\n\
VResolution 72 div neg scale magscale{DVImag dup scale}if 0 setgray}N\n\
/@beginspecial{/SpecialSave save N SDict begin gsave normalscale\n\
currentpoint TR @SpecialDefaults count /ocount X /dcount countdictstack\n\
N}N /@setspecial{CLIP 1 eq{newpath 0 0 moveto hs 0 rlineto 0 vs rlineto\n\
hs neg 0 rlineto closepath clip}if ho vo TR hsc vsc scale ang rotate\n\
rwiSeen{rwi urx llx sub div rhiSeen{rhi ury lly sub div}{dup}ifelse\n\
scale llx neg lly neg TR}{rhiSeen{rhi ury lly sub div dup scale llx neg\n\
lly neg TR}if}ifelse CLIP 2 eq{newpath llx lly moveto urx lly lineto urx\n\
ury lineto llx ury lineto closepath clip}if /showpage{}N /erasepage{}N\n\
/copypage{}N /setpagedevice{pop}def newpath}N /@endspecial{count ocount\n\
sub{pop}repeat countdictstack dcount sub{end}repeat grestore SpecialSave\n\
restore end}N /@xdvisavestate{userdict /xdvi$sav save put}N /@defspecial\n\
{SDict begin}N /@fedspecial{end @xdvisavestate}B end\n";

 int	psheaderlen	= 3075;
