#! /bin/bash
# CXXLD.sh.  Generated by configure.
set -- g++ -Wreturn-type -Wno-unknown-pragmas -Wno-write-strings "$@" -nodefaultlibs -Wl,-Bstatic -lstdc++ -Wl,-Bdynamic -lm -lgcc_eh -lgcc -lc -lgcc_eh -lgcc
echo "$0:" "$@"
exec "$@"
